DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS cards;
DROP TABLE IF EXISTS bank_accounts;
DROP TABLE IF EXISTS clients;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT,
	is_admin VARCHAR(12) NOT NULL,
	login VARCHAR(6) NOT NULL,
	password VARCHAR(6) NOT NULL,
	UNIQUE(login),
	PRIMARY KEY(id)
) ENGINE INNODB;


CREATE TABLE clients (
	id INT NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(10) NOT NULL,
	last_name VARCHAR(12) NOT NULL,
	surname VARCHAR(14) NOT NULL,
	user_id INT NOT NULL,
	
	FOREIGN KEY (user_id) REFERENCES users(id)
	ON DELETE CASCADE ON UPDATE CASCADE,

	PRIMARY KEY(id)
) ENGINE INNODB;


CREATE TABLE bank_accounts (
	id INT NOT NULL AUTO_INCREMENT,
	balance INT NOT NULL,
	is_blocked TINYINT NOT NULL,	

	PRIMARY KEY(id)
) ENGINE INNODB;


CREATE TABLE cards (
	id INT NOT NULL AUTO_INCREMENT,
	card_number VARCHAR(16) NOT NULL,
	account_id INT NOT NULL,
	client_id INT NOT NULL,
	
	FOREIGN KEY (account_id) REFERENCES bank_accounts(id)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (client_id) REFERENCES clients(id)
	ON DELETE CASCADE ON UPDATE CASCADE,

	PRIMARY KEY(id)
) ENGINE INNODB;


CREATE TABLE transactions (
	id INT NOT NULL AUTO_INCREMENT,
	tr_date DATE NOT NULL,
	tr_sum INT NOT NULL,
	tr_type TINYINT NOT NULL,
	card_id INT NOT NULL,
	client_id INT NOT NULL,

	
	FOREIGN KEY (card_id) REFERENCES cards(id)
	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (client_id) REFERENCES clients(id)
	ON DELETE CASCADE ON UPDATE CASCADE,

	PRIMARY KEY(id)
) ENGINE INNODB;